#!/usr/bin/env bash
# Regenerate app/data/icon_manifest.js from whatever is in img/icons/.
# EN: run this after adding icon files to img/icons/. Requires bash (Git Bash on Windows).
# RU: запустите после добавления иконок в img/icons/. Нужен bash (Git Bash в Windows).
set -euo pipefail
cd "$(dirname "$0")/.."
{
printf '/* AUTO-GENERATED by tools/gen-icon-manifest.sh - do not edit by hand. */\n'
printf '(function (V3) {\n'
printf "  'use strict';\n"
printf '  V3.iconManifest = {\n'
printf '    base: "../img/icons/",\n'
printf '    files: [\n'
find img/icons -type f \( -name '*.png' -o -name '*.svg' \) | sed 's|^img/icons/||' | sort | while IFS= read -r rel; do
  cat=$(printf '%s' "$rel" | awk -F/ '{print $1}')
  fname=$(basename "$rel")
  key=$(printf '%s' "$fname" | sed -e 's/^120px-//' -e 's/\.[a-zA-Z]*$//')
  printf '      ["%s","%s","%s"],\n' "$cat" "$rel" "$key"
done
printf '    ]\n'
printf '  };\n'
printf '})(window.V3);\n'
} > app/data/icon_manifest.js
echo "Wrote app/data/icon_manifest.js ($(grep -c '\["' app/data/icon_manifest.js) icons)"
